---
plugin: amazon.aws.aws_ec2
regions:
  - eu-north-1
groups:
  controlnodes: inventory_hostname.startswith('controlnode')
  windowsclients: inventory_hostname.startswith('windows-client')
  windowsservers: inventory_hostname.startswith('windows-server')
  dcvservers: inventory_hostname.startswith('dcv-server')
keyed_groups:
  - key: ec2_tags
    prefix: 'group'
#compose:
#  ansible_host: instance_id
route53_enabled: true
route53_hostnames:
  - ansible-windows.training.scinnolab.net
use_ssm_inventory: true
...

